INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (1, 'Barca', 34.33, 11, 3);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (2, 'Spaghetti di riso verdure e gamberetti', 4.5, 2, 3);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (3, 'Involtini di gamberi', 5.5, 11, 3);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (4, 'Dosa e Masala Dosa', 7, 14, 2);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (5, 'Kashmiri Aloo Dum', 8, 7, 2);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (6, 'Pollo Tikka Masala', 12, 14, 2);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (7, 'Pizza Margherita', 4.5, 1, 1);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (8, 'Pizza Bolognose', 7.7, 1, 1);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (9, 'Pizza Capricciosa', 7, 1, 1);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (10, 'Pizza estiva', 8, 1, 1);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (11, 'Pizza Rustica', 7, 1, 1);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (12, 'Piazza Pippo', 8, 1, 1);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (13, 'Tagliata di montone', 30, 3, 4);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (14, 'Contorno di campo', 7, 8, 4);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (15, 'Pizza anti-ananas', 7, 1, 5);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (16, 'Poldo', 12, 4, 5);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (17, 'Giro alcolico misto', 30, 18, 6);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (18, 'Chardonnay invecchiato anno "0"', 1000000000, 17, 7);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (19, 'Pesce Divino', 1000000000, 6, 7);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (20, 'Tartare di Tonno', 15, 6, 6);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (21, 'Gran Crispy McBacon®', 8.99, 4, 8);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (22, 'Big Mac®', 8.99, 4, 8);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (23, 'McChicken® Originale', 7.99, 4, 8);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (24, 'Caesar Salad con pollo croccante', 5.99, 8, 8);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (25, 'Fanta', 1.99, 19, 8);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (26, 'Caffè', 1.99, 20, 8);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (27, 'BACON KING 3.0 RANCH SAUCE', 6.99, 4, 9);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (28, 'KING FUSION® NESCAFÈ®', 1.99, 16, 9);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (29, 'Coca Cola', 1.99, 19, 9);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (30, 'Caffè', 1.99, 20, 9);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (31, 'Pesce Spada', 10.99, 6, 10);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (32, 'Tignanello', 20.99, 17, 10);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (33, 'Vega Sicilia', 55, 17, 10);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (34, 'Caffè', 1.99, 20, 10);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (35, 'Paella', 10.5, 10, 10);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (36, 'Sushi', 10.6, 11, 10);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (37, 'Tortino al Cioccolato', 10.4, 16, 10);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (38, 'Pizza Margherita', 15.9, 1, 10);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (39, 'Tartar di Carne', 11, 3, 11);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (40, 'Crepes ', 6, 16, 11);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (41, 'Amatriciana', 12, 2, 12);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (42, 'Spada e Ciliegino', 24, 6, 12);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (43, 'Pesto Doppio', 9, 2, 12);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (44, 'Hot Burger ', 7, 1, 13);
INSERT INTO noteatyet.piatti (id, nome, prezzo, categoria_id, ristorante_id) VALUES (45, 'Pollo e patate', 7, 3, 14);