INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (1, 'scampi', 1);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (2, 'alghe', 1);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (3, 'tonno', 1);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (4, 'riso', 1);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (5, 'edamame', 1);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (6, 'salmone', 1);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (7, 'spaghetti di riso', 2);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (8, 'mix verdure', 2);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (9, 'gamberetti', 2);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (10, 'uova', 2);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (11, 'Pastella', 3);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (12, 'gamberi', 3);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (13, 'verze', 3);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (14, 'patate', 4);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (15, 'coriandolo', 4);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (16, 'riso', 4);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (17, 'lenticchie', 4);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (18, 'curcuma', 4);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (19, 'curry', 4);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (20, 'cipolle', 4);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (21, 'patate', 5);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (22, 'salsa yougurt', 5);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (23, 'pomodoro', 5);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (24, 'curry', 5);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (25, 'mix di spezie', 5);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (26, 'yougurt', 6);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (27, 'pollo', 6);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (28, 'spezie', 6);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (29, 'masala', 6);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (30, 'pomodoro', 7);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (31, 'mozzarella', 7);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (32, 'pomodoro', 8);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (33, 'mozzarella', 8);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (34, 'mortadella IGP', 8);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (35, 'aceto balsamico', 8);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (36, 'rucola', 8);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (37, 'mozzarella', 9);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (38, 'pomodoro', 9);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (39, 'prosciutto', 9);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (40, 'funghi', 9);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (41, 'carciofi', 9);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (42, 'pomodoro', 10);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (43, 'mozzarella', 10);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (44, 'rucola', 10);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (45, 'pomodoro a fette', 10);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (46, 'mozzarella di bufala', 10);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (47, 'pomodoro', 11);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (48, 'mozzarella', 11);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (49, 'pancetta nostrana', 11);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (50, 'grana in polvere', 11);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (51, 'pomodoro', 12);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (52, 'salame piccante', 12);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (53, 'mozzarella', 12);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (54, 'olive nere', 12);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (55, 'scamorza', 12);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (92, 'Spezie di campo', 13);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (93, 'Pepe', 13);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (94, 'Olio extravergine di oliva', 13);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (95, 'Sale', 13);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (96, 'Carne di montone', 13);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (97, 'Mix di insalate di campo', 14);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (98, 'Salsa', 15);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (99, 'Basilico', 15);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (100, 'Olio extravergine di oliva', 15);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (101, 'Pizza', 15);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (102, 'Sale', 15);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (103, 'NO ANANAS', 15);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (104, 'Salsa BBQ', 16);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (105, 'Insalata', 16);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (106, 'Sale affumicato', 16);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (107, 'Hamburger', 16);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (108, 'Pomodorini', 16);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (109, 'Panino', 16);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (110, 'Chupito di Whiskey', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (111, 'Chupito di Rum', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (112, 'Chupito di Vodka', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (113, 'Chupito di Tequila', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (114, 'Chupito di Assenzio', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (115, 'Chupito di Limoncello', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (116, 'Chupito di Cognac', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (117, 'Chupito di Gin', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (118, 'Chiamata del 118 incluso', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (119, 'Chupito di Latte della Suocera', 17);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (120, 'Vino direttamente pestato ed imbottigliato dall'' Altissimo', 18);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (121, 'Direttamente pescato dall'' Altissimo', 19);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (122, 'Pesce congelato da 2000 anni', 19);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (123, 'Cardamomo', 20);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (124, 'Lime', 20);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (125, 'Tonno fresco', 20);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (126, 'Pepe rosa', 20);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (127, 'Olio extravergine di oliva ', 20);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (170, 'Carne 100% Bovina', 21);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (171, 'Bacon', 21);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (172, 'Salsa', 21);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (173, 'Pane', 21);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (174, 'Formaggio', 21);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (175, 'Pane', 22);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (176, 'Carne 100% Bovina', 22);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (177, 'Formaggio', 22);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (178, 'Insalata', 22);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (179, 'Salsa', 22);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (180, 'Cipolla', 22);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (181, 'Cetriolo', 22);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (182, 'Pane', 23);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (183, '100% Pollo', 23);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (184, 'Insalata ', 23);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (185, 'Salsa', 23);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (186, 'Insalata', 24);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (187, 'Pollo', 24);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (188, 'Olio', 24);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (189, 'Pomodorini', 24);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (190, 'Pane', 27);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (191, 'Bacon', 27);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (192, 'Carne', 27);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (193, 'Formaggio', 27);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (194, 'Salsa', 27);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (195, 'Gelato', 28);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (196, 'Uova', 28);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (197, 'Panna', 28);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (198, 'Latte', 28);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (199, 'Orzo', 28);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (200, 'Olio', 31);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (201, 'Pesce', 31);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (202, 'Limone', 31);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (203, 'Riso', 35);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (204, 'Pesce', 35);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (205, 'Pomodoro', 35);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (206, 'Riso', 36);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (207, 'Alga', 36);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (208, 'Pesce', 36);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (209, 'Tortino', 37);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (210, 'Cioccolato', 37);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (211, 'Pizza Pane', 38);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (212, 'Sugo', 38);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (213, 'Mozzarella', 38);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (214, 'Basilico', 38);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (215, 'Olio', 38);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (216, 'limone', 39);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (217, 'vitello', 39);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (218, 'uova', 39);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (219, 'pepe,sale', 39);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (220, 'farina', 40);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (221, 'latte', 40);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (222, 'fragole', 40);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (223, 'cioccolato', 40);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (224, 'panna', 40);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (225, 'cacao in polvere', 40);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (226, 'bucatini', 41);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (227, 'sugo', 41);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (228, 'cipolla', 41);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (229, 'guanciale', 41);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (230, 'pesce spada', 42);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (231, 'ciliegino', 42);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (232, 'melanzane', 42);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (233, 'menta', 42);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (234, 'basilico', 43);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (235, 'ciliegino', 43);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (236, 'mandorle', 43);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (237, 'aglio', 43);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (238, 'pinoli', 43);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (239, 'melanzane ', 43);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (240, 'burger di vitello', 44);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (241, 'cipolla', 44);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (242, 'lattuga', 44);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (243, 'pollo ', 45);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (244, 'rosmarino', 45);
INSERT INTO noteatyet.ingredienti (id, nome, piatto_id) VALUES (245, 'patate a forno', 45);